# Nombre del workflow, aparecerá en la pestaña "Actions" de tu repositorio
name: Scrape Oposiciones Data

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run the scraper
        run: python3 scraper.py

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Chore: Update scraped data"
          file_pattern: "src/data/tribunal1_inscritos.json src/data/tribunal2_inscritos.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"