
# Nombre del workflow, aparecer치 en la pesta침a "Actions" de tu repositorio
name: Scrape Oposiciones Data

# Disparadores: Cu치ndo se debe ejecutar este workflow
on:
  # 1. Ejecuci칩n programada (schedule) usando formato cron
  # Este ejemplo se ejecuta todos los d칤as a las 1:00 AM UTC
  schedule:
    - cron: '0 1 * * *'
  
  # 2. Ejecuci칩n manual (workflow_dispatch)
  # A침ade un bot칩n "Run workflow" en la pesta침a Actions para ejecutarlo cuando quieras
  workflow_dispatch:

# Tareas (jobs) que se van a ejecutar
jobs:
  scrape:
    # El tipo de m치quina virtual donde se ejecutar치 el c칩digo
    runs-on: ubuntu-latest

    # Pasos (steps) que se ejecutar치n en orden
    steps:
      # 1. Descarga tu c칩digo del repositorio a la m치quina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Puedes usar una versi칩n m치s reciente si quieres

      # 3. Instala las librer칤as necesarias desde requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Instala las dependencias para que Selenium y Chrome funcionen en el servidor
      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 5. Ejecuta el script de scraping
      - name: Run the scraper
        run: python3 scraper.py

      # 6. Sube los ficheros JSON actualizados al repositorio
      # Este paso es la clave: detecta si los JSON han cambiado y, si es as칤,
      # crea un nuevo commit y lo sube a tu rama principal (main/master).
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "游늵 Chore: Update scraped data"
          # Aseg칰rate de que los nombres coincidan con los de tu script
          file_pattern: tribunal1_inscritos.json tribunal2_inscritos.json
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"