name: Scrape Oposiciones Data

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Spanish language pack & Set Locale
        run: |
          sudo apt-get install -y language-pack-es
          sudo locale-gen es_ES.UTF-8
          echo "LANG=es_ES.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=es_ES.UTF-8" >> $GITHUB_ENV

      - name: Run the scraper
        run: python3 scraper.py

      - name: Run the convocatorias scraper
        run: python3 scraper_convocatorias.py

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          commit_message: "📊 Chore: Update scraped data"
          file_pattern: "src/data/tribunal1_inscritos.json src/data/tribunal2_inscritos.json src/data/convocatorias.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"